version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
      - /app/node_modules
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    command: sh -c "chmod 644 /etc/mysql/my.cnf && mysqld"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mysql-config/mysql.cnf:/etc/mysql/my.cnf
#      - ./mysql-entrypoint.sh:/docker-entrypoint-initdb.d/mysql-entrypoint.sh
    restart: unless-stopped


volumes:
  mysql_data:
