version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_configs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db_configs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    restart: unless-stopped

  locust:
    build: ./locust
    ports:
      - "8089:8089"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TARGET_HOST=http://app:${PORT}
    depends_on:
      - app
      - mysql
    command: [ "locust", "-f", "locustfile.py", "--host=http://app:${PORT}" ]

volumes:
  mysql_data:
