services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pastebin
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3308:3306"
    networks:
      - default

  pastebin-soa:
    container_name: pastebin-soa
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - SPRING_PROFILE=docker
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=pastebin
      - MYSQL_USERNAME=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3306
    networks:
      - default

networks:
  default:
    name: pastebin-soa

volumes:
  mysql-data: