spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/pastebin
    username: root
    password: "huyfcbayern"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true  #log sql query
    hibernate:
      ddl-auto: none # or none